name: my__PIPELINE

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice    
        options:
          - apply
          - destroy

jobs:
  apply:
    name: Apply Infrastructure
    if: github.event.inputs.action == 'apply' || github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Authenticate to GCP
        id: 'auth'
        uses: 'google-github-actions/auth@v0.3.1'
        with:
          create_credentials_file: 'true'
          workload_identity_provider: projects/1075213033479/locations/global/workloadIdentityPools/iac-nilesh-pool/providers/iac-nilesh-pro-id-2
          service_account: june-service-account-oidc@nileshfirst.iam.gserviceaccount.com

      - name: Zip Cloud Function code
        run: |
          cd terraform/modules/vendor/cloudFunction
          zip -r function.zip main.py requirements.txt

      - name: Initialize Terraform
        run: |
          cd nileshIAC
          terraform init

      - name: Plan Terraform
        run: |
          cd nileshIAC
          terraform plan -var-file="config/project.json"

      - name: Apply Terraform
        run: |
          cd nileshIAC
          terraform apply -var-file="config/project.json" -auto-approve

  destroy:
    name: Destroy Infrastructure
    if: github.event.inputs.action == 'destroy'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Authenticate to GCP
        id: 'auth'
        uses: 'google-github-actions/auth@v0.3.1'
        with:
          create_credentials_file: 'true'
          workload_identity_provider: projects/1075213033479/locations/global/workloadIdentityPools/iac-nilesh-pool/providers/iac-nilesh-pro-id-2
          service_account: june-service-account-oidc@nileshfirst.iam.gserviceaccount.com

      - name: Initialize Terraform
        run: |
          cd nileshIAC
          terraform init
      - name: Plan Terraform
        run: |
          cd nileshIAC
          terraform plan -var-file="config/project.json"

      - name: Destroy Terraform
        run: |
          cd nileshIAC
          terraform destroy -var-file="config/project.json" -auto-approve